# Generated by Django 5.2.7 on 2025-10-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lap_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laps.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laps.user')),
            ],
            options={
                'db_table': 'laps',
            },
        ),
    ]
