# Generated by Django 5.2.7 on 2025-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
